

export const TYPES ={
    ADD_FIRST_FILTER:"ADD_FIRST_FILTER"
    // REMOVE_ONE_FROM_CART:"REMOVE_ONE_FROM_CART",
    // REMOVE_ALL_FROM_CART:"REMOVE_ALL_FROM_CART",
    // CLEAN_CART:"CLEAN_CART"
}