export const FETCH_ULTIMAS_FOTOS_CAMARAS = "FETCH_ULTIMAS_FOTOS_CAMARAS"
export const PRUEBA = "PRUEBA"
export const ACTUALIZAR_MUNICIPIO = "ACTUALIZAR_MUNICIPIO"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"

//ESTACIONES
export const FETCH_LISTADO_ESTACIONES = "FETCH_LISTADO_ESTACIONES"
export const POST_NUEVA_ESTACION = "POST_NUEVA_ESTACION"
export const FETCH_ESTACION_ACTUAL = "FETCH_ESTACION_ACTUAL"
export const CLEAR_ESTACION_ACTUAL = "CLEAR_ESTACION_ACTUAL"


export const FETCH_LISTADO_JARDINES = "FETCH_LISTADO_JARDINES"

export const FETCH_LISTADO_ALIMENTACIONES = "FETCH_LISTADO_ALIMENTACIONES"


export const FETCH_LISTADO_REDES = "FETCH_LISTADO_REDES"


//COMPONENTES
export const FETCH_LISTADO_COMPONENTES = "FETCH_LISTADO_COMPONENTES"
//export const FETCH_COMPONENTE_NUEVO = "FETCH_COMPONENTE_NUEVO"
export const FETCH_COMPONENTE_ACTUAL = "FETCH_COMPONENTE_ACTUAL"
export const UPDATE_COMPONENTE_ACTUAL = "UPDATE_COMPONENTE_ACTUAL"
export const CREATE_NUEVO_COMPONENTE = "CREATE_NUEVO_COMPONENTE"

//MARCAS
export const FETCH_LISTADO_MARCAS = "FETCH_LISTADO_MARCAS"

//TIPOS COMPONENTE
export const FETCH_LISTADO_TIPOS_COMPONENTE = "FETCH_LISTADO_TIPOS_COMPONENTE"

//GARANTIAS
export const FETCH_LISTADO_GARANTIAS = "FETCH_LISTADO_GARANTIAS"

//CARTERAS
export const FETCH_LISTADO_CARTERAS = "FETCH_LISTADO_CARTERAS"

//NOSENSORES
export const FETCH_LISTADO_NOSENSORES = "FETCH_LISTADO_NOSENSORES"
export const FETCH_NOSENSOR_ACTUAL = "FETCH_NOSENSOR_ACTUAL"

//TIPOS NOSENSOR
export const FETCH_LISTADO_TIPOS_NOSENSOR = "FETCH_LISTADO_TIPOS_NOSENSOR"

//MUEBLES
export const FETCH_LISTADO_MUEBLES = "FETCH_LISTADO_MUEBLES"
export const FETCH_MUEBLE_ACTUAL = "FETCH_MUEBLE_ACTUAL"
export const UPDATE_MUEBLE_ACTUAL = "UPDATE_MUEBLE_ACTUAL"
export const CREATE_NUEVO_MUEBLE = "CREATE_NUEVO_MUEBLE"


//CONSUMIBLES
export const FETCH_LISTADO_CONSUMIBLES = "FETCH_LISTADO_CONSUMIBLES"
export const FETCH_CONSUMIBLE_ACTUAL = "FETCH_CONSUMIBLE_ACTUAL"
export const UPDATE_CONSUMIBLE_ACTUAL = "UPDATE_CONSUMIBLE_ACTUAL"
export const CREATE_NUEVO_CONSUMIBLE = "CREATE_NUEVO_CONSUMIBLE"